# Book settings
title: Proyek Analisis Data & Machine Learning  # Ganti dengan judul pilihan Anda
author: Abror Ulil                          # Ganti dengan nama Anda
logo: pp.png

# Pengaturan Eksekusi
execute:
  execute_notebooks: "auto"  # Tetap "off" agar build lebih cepat jika notebook sudah di-run

# Konfigurasi Repositori (BAGIAN PALING PENTING)
repository:
  url: https://github.com/abrorulil/proyek  # URL repositori Anda
  path_to_book: .                           # Titik (.) karena notebook Anda ada di folder utama
  branch: main                              # Branch sumber Anda adalah main

# Fitur HTML
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: |
    <a href="https://abrorulil.github.io/proyek/intro.html">Halaman Utama</a>

# File yang diabaikan
exclude:
  - tugas/references.bib
